# Ds Practical 1
Aim : Data Frames and Basic Data Pre-processing\
A. Read data from CSV and JSON files into a data frame.\
B. Perform basic data pre-processing tasks such as handling missing values and outliers.\
C. Manipulate and transform data using functions like filtering, sorting, and grouping.

# A. Read data from CSV and JSON files into a data frame.

# Loading Dataset


In [ ]:
from sklearn import datasets
# load digits dataset
digits = datasets.load_digits()
iris = datasets.load_iris()
# Feature matrix
features1 = digits.data
target1 = digits.target
# For iris
features2 = iris.data
target2 = iris.target
#Viewing the first observation
print('digits dataset:',features1[0])
print('iris dataset:',features2[0])

digits dataset: [ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
iris dataset: [5.1 3.5 1.4 0.2]


# Creating simulated Dataset

In [ ]:
#load library
from sklearn.datasets import make_regression
from sklearn.datasets import make_classification
from sklearn.datasets import make_blobs

#generate feature , target , coeffient
feature, target, coefficient = make_regression(n_samples = 100,
                                               n_features = 3,
                                               n_informative = 3,
                                               n_targets = 1,
                                               noise = 0.0,
                                               coef = True,
                                               random_state = 1)
features2, target2 = make_classification(
    n_samples = 100,
    n_features = 3,
    n_informative = 3,
    n_redundant = 0,
    n_classes = 2,
)
features3, target3 = make_blobs(
    n_samples = 100,
    n_features = 2,
    centers = 2,
    cluster_std = 1,
    random_state = 1
)
#For Regression
#View feature matrix and target vector
print("For Regression : ")
print('feature matrix\n',feature[:3])
print('target vector\n',target[:3])
#For Classification
print("For Classification : ")
print('feature matrix\n',features2[:3])
print('target vector\n',target2[:3])
#For Clustering
print("For Clustering : ")
print('feature matrix\n',features3[:3])
print('target vector\n',target3[:3])

For Regression : 
feature matrix
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
target vector
 [-10.37865986  25.5124503   19.67705609]
For Classification : 
feature matrix
 [[-1.55240316 -1.81614421  2.90342015]
 [ 0.46995946  1.59544915 -2.3332013 ]
 [-2.03283678  1.09321544  0.53255535]]
target vector
 [1 0 0]
For Clustering : 
feature matrix
 [[-0.79415228  2.10495117]
 [-9.15155186 -4.81286449]
 [-3.10367371  3.90202401]]
target vector
 [0 1 0]


# Loading Files


In [ ]:
import pandas as pd
df = pd.read_excel('/content/CardioGoodFitness.xlsx')
print('Excel Format Dataset:\n',df.head(2))
df2 = pd.read_json('/content/iris.json')
print('Json Format Dataset:\n',df2.head(2))
df3 = pd.read_csv('/content/diabetes.csv')
print('CSV Format Dataset:\n',df3.head(2))

Excel Format Dataset:
   Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18   Male         14        Single      3        4   29562    112
1   TM195   19   Male         15        Single      2        3   31836     75
Json Format Dataset:
    sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
CSV Format Dataset:
    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  


# B. Perform basic data pre-processing tasks such as handling missing values and outliers.

In [ ]:
# Checking for missing values
import pandas as pd
df = pd.read_csv("/content/Titanic-Dataset.csv")
# Find the missing values from each column
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [ ]:
# Replacing with the previous value – forward fill (time series example)
import pandas as pd
import numpy as np
test = pd.Series(range(6))
test.loc[2:4] = np.nan
test

0    0.0
1    1.0
2    NaN
3    NaN
4    NaN
5    5.0
dtype: float64

In [ ]:
# Interpolation example
test.interpolate()


0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
dtype: float64

In [ ]:
# Impute most frequent for categorical feature
import pandas as pd
import numpy as np
X = pd.DataFrame({'Shape':['square', 'square', 'oval', 'circle', np.nan]})
X
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
imputer.fit_transform(X)


array([['square'],
       ['square'],
       ['oval'],
       ['circle'],
       ['square']], dtype=object)

In [ ]:
# Impute as the constant 'missing'
imputer = SimpleImputer(strategy='constant', fill_value='missing')
imputer.fit_transform(X)


array([['square'],
       ['square'],
       ['oval'],
       ['circle'],
       ['missing']], dtype=object)

In [ ]:
# Multivariate example (Titanic subset)
import pandas as pd
df = pd.read_csv('/content/Titanic-Dataset.csv', nrows=6)
cols = ['SibSp', 'Fare', 'Age']
X = df[cols]
X


SibSp     Fare   Age
0      1   7.2500  22.0
1      1  71.2833  38.0
2      0   7.9250  26.0
3      1  53.1000  35.0
4      0   8.0500  35.0
5      0   8.4583   NaN

In [ ]:
# IterativeImputer (multivariate imputation)
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
impute_it = IterativeImputer()
impute_it.fit_transform(X)


array([[ 1.        ,  7.25      , 22.        ],
       [ 1.        , 71.2833    , 38.        ],
       [ 0.        ,  7.925     , 26.        ],
       [ 1.        , 53.1       , 35.        ],
       [ 0.        ,  8.05      , 35.        ],
       [ 0.        ,  8.4583    , 28.50639495]])

In [ ]:
# SimpleImputer univariate mean example
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit([[1, 2], [np.nan, 3], [7, 6]])

# transform example
X = [[np.nan, 2], [6, np.nan], [7, 6]]
print(imp.transform(X))


[[4.         2.        ]
 [6.         3.66666667]
 [7.         6.        ]]


In [ ]:
# KNNImputer example
from sklearn.impute import KNNImputer
impute_knn = KNNImputer(n_neighbors=2)
impute_knn.fit_transform(X)


array([[7., 2.],
       [6., 6.],
       [7., 6.]])

In [ ]:
# Using missingness as a feature (indicator)
import pandas as pd
import numpy as np
X = pd.DataFrame({'Age':[20, 30, 10, np.nan, 10]})
X

from sklearn.impute import SimpleImputer
# impute the mean
imputer = SimpleImputer()
imputer.fit_transform(X)

# with indicator
imputer = SimpleImputer(add_indicator=True)
imputer.fit_transform(X)


array([[20. ,  0. ],
       [30. ,  0. ],
       [10. ,  0. ],
       [17.5,  1. ],
       [10. ,  0. ]])

# C. Manipulate and transform data using functions like filtering, sorting, and grouping.

In [ ]:
import pandas as pd

In [ ]:
# Load the data
df = pd.read_csv("/content/Titanic-Dataset.csv")

# show first two rows
print(df.head(2))

# show dimensions
print("Dimensions: {}".format(df.shape))

# show statistics
df.describe()

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C  
Dimensions: (891, 12)


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
# select the first row
print(df.iloc[0])

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: Braund, Mr. Owen Harris, dtype: object


In [ ]:
# select three rows (index 1, 2, 3)
print(df.iloc[1:4])

                                                    PassengerId  Survived  \
Name                                                                        
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Heikkinen, Miss. Laina                                        3         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   

                                                    Pclass  \
Name                                                         
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1   
Heikkinen, Miss. Laina                                   3   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1   

                                                                                                 Name  \
Name                                                                                                    
Cumings, Mrs. John Bradley (Florence Briggs Tha...  Cumings, Mrs. John Bradley (Florence Brig

In [ ]:
# all rows up to and including the fourth row (index 0, 1, 2, 3)
print(df.iloc[:4])

                                                    PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Heikkinen, Miss. Laina                                        3         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   

                                                    Pclass  \
Name                                                         
Braund, Mr. Owen Harris                                  3   
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1   
Heikkinen, Miss. Laina                                   3   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1   

                                                                                                 Name  \
Name                                                       

In [ ]:
# set index to 'Name' column
df = df.set_index(df ['Name'])
df

PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Heikkinen, Miss. Laina                                        3         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   
Allen, Mr. William Henry                                      5         0   
...                                                         ...       ...   
Montvila, Rev. Juozas                                       887         0   
Graham, Miss. Margaret Edith                                888         1   
Johnston, Miss. Catherine Helen "Carrie"                    889         0   
Behr, Mr. Karl Howell                                       890         1   
Dooley, Mr. Patrick                                         891         0   

                                                    Pclass  \
Name                                                         
Braund, Mr. Owen Harris                                  3   
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1   
Heikkinen, Miss. Laina                                   3   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1   
Allen, Mr. William Henry                                 3   
...                                                    ...   
Montvila, Rev. Juozas                                    2   
Graham, Miss. Margaret Edith                             1   
Johnston, Miss. Catherine Helen "Carrie"                 3   
Behr, Mr. Karl Howell                                    1   
Dooley, Mr. Patrick                                      3   

                                                                                                 Name  \
Name                                                                                                    
Braund, Mr. Owen Harris                                                       Braund, Mr. Owen Harris   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  Cumings, Mrs. John Bradley (Florence Briggs Th...   
Heikkinen, Miss. Laina                                                         Heikkinen, Miss. Laina   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             Futrelle, Mrs. Jacques Heath (Lily May Peel)   
Allen, Mr. William Henry                                                     Allen, Mr. William Henry   
...                                                                                               ...   
Montvila, Rev. Juozas                                                           Montvila, Rev. Juozas   
Graham, Miss. Margaret Edith                                             Graham, Miss. Margaret Edith   
Johnston, Miss. Catherine Helen "Carrie"                     Johnston, Miss. Catherine Helen "Carrie"   
Behr, Mr. Karl Howell                                                           Behr, Mr. Karl Howell   
Dooley, Mr. Patrick                                                               Dooley, Mr. Patrick   

                                                       Sex   Age  SibSp  \
Name                                                                      
Braund, Mr. Owen Harris                               male  22.0      1   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  female  38.0      1   
Heikkinen, Miss. Laina                              female  26.0      0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)        female  35.0      1   
Allen, Mr. William Henry                              male  35.0      0   
...                                                    ...   ...    ...   
Montvila, Rev. Juozas                                 male  27.0      0   
Graham, Miss. Margaret Edith                        female  19.0      0   
Johnston, Miss. Catherine Helen "Carrie"            female   NaN      1   
Behr, Mr. Karl Howell                               

In [ ]:
# show row using the new index (Name)
df.loc['Braund, Mr. Owen Harris']

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: Braund, Mr. Owen Harris, dtype: object

In [ ]:
df = pd.read_csv("/content/Titanic-Dataset.csv")
# select top two rows where column 'Sex' is 'female'
df [df ['Sex'] == 'female'].head(2)
# multiple conditions (female AND age >= 55)
df [(df ['Sex'] == 'female') & (df ['Age'] >= 55)]

PassengerId  Survived  Pclass  \
11            12         1       1   
15            16         1       2   
195          196         1       1   
268          269         1       1   
275          276         1       1   
366          367         1       1   
483          484         1       3   
772          773         0       2   
829          830         1       1   
879          880         1       1   

                                                 Name     Sex   Age  SibSp  \
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
195                              Lurette, Miss. Elise  female  58.0      0   
268     Graham, Mrs. William Thompson (Edith Junkins)  female  58.0      0   
275                 Andrews, Miss. Kornelia Theodosia  female  63.0      1   
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  female  60.0      1   
483                            Turkula, Mrs. (Hedwig)  female  63.0      0   
772                                 Mack, Mrs. (Mary)  female  57.0      0   
829         Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   
879     Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   

     Parch       Ticket      Fare Cabin Embarked  
11       0       113783   26.5500  C103        S  
15       0       248706   16.0000   NaN        S  
195      0     PC 17569  146.5208   B80        C  
268      1     PC 17582  153.4625  C125        S  
275      0        13502   77.9583    D7        S  
366      0       110813   75.2500   D37        C  
483      0         4134    9.5875   NaN        S  
772      0  S.O./P.P. 3   10.5000   E77        S  
829      0       113572   80.0000   B28      NaN  
879      1        11767   83.1583   C50        C

In [ ]:
# replace any instance of 'female' with 'Woman' in the 'Sex' column
df ['Sex'].replace('female', 'Woman').head(2)

# replace multiple instances ('female' with 'Woman', 'male' with 'Man')
df ['Sex'].replace(['female', 'male'], ['Woman', 'Man']).head(5)

# replace all instances of value 1 with string "One" across the DataFrame
df.replace(1, "One").head(2)

PassengerId Survived Pclass  \
0         One        0      3   
1           2      One    One   

                                                Name     Sex   Age SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0   One   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   One   

  Parch     Ticket     Fare Cabin Embarked  
0     0  A/5 21171   7.2500   NaN        S  
1     0   PC 17599  71.2833   C85        C

In [ ]:
# rename a single column
df.rename(columns={'PClass': 'Passenger Class'}).head(2)

# rename multiple columns
df.rename(columns={'PClass': 'Passenger Class', 'Sex': 'Gender'}).head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [ ]:
print('Maximum: {}'.format(df['Age'].max()))
print('Minimum: {}'.format(df ['Age'].min()))
print('Mean: {}'.format(df ['Age'].mean()))
print('Sum: {}'.format(df['Age'].sum()))
print('Count: {}'.format(df['Age'].count()))


Maximum: 80.0
Minimum: 0.42
Mean: 29.69911764705882
Sum: 21205.17
Count: 714


In [ ]:
print("Variance:", df['Fare'].var())
print("Standard Deviation:", df['Fare'].std())
print("Kurtosis:", df['Fare'].kurt())
print("Skewness:", df['Fare'].skew())


Variance: 2469.436845743117
Standard Deviation: 49.693428597180905
Kurtosis: 33.39814088089868
Skewness: 4.787316519674893


In [ ]:
# unique will return an array of all unique values in a column
df ['Sex'].unique()

# value_counts will display all unique values with the number of times each value appears
df ['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
# select missing values, show 2 rows
df [df ['Age'].isnull()].head(2)

PassengerId  Survived  Pclass                          Name   Sex  Age  \
5             6         0       3              Moran, Mr. James  male  NaN   
17           18         1       2  Williams, Mr. Charles Eugene  male  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583   NaN        Q  
17      0      0  244373  13.0000   NaN        S

In [ ]:
# axis=1 means the column axis
df.drop('Age', axis=1).head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   

      Ticket     Fare Cabin Embarked  
0  A/5 21171   7.2500   NaN        S  
1   PC 17599  71.2833   C85        C

In [ ]:
# create new dataframe excluding the rows where 'Sex' is 'male'
df [df ['Sex'] != 'male'].head(2)

# delete a row by matching a unique value ('Name')
df [df ['Name'] != 'Allison, Miss Helen Loraine'].head(2)
# delete a row by index (index 0)
df [df.index != 0].head(2)

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [ ]:
# group by 'Sex' and calculate the mean of all numerical columns
df.groupby('Sex')[df.select_dtypes(include='number').columns].mean()

# group by 'Survived' and count the number of 'Name' entries
df.groupby('Survived') ['Name'].count()

# group by multiple columns ('Sex' and 'Survived') and calculate the mean of 'Age'
df.groupby(['Sex', 'Survived']) ['Age'].mean()

Sex     Survived
female  0           25.046875
        1           28.847716
male    0           31.618056
        1           27.276022
Name: Age, dtype: float64

In [ ]:
# for loop
for name in df ['Name'] [0:2]:
    print(name.upper())

# list comprehension (more "pythonic")
[name.upper() for name in df ['Name'] [0:2]]

BRAUND, MR. OWEN HARRIS
CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS THAYER)


['BRAUND, MR. OWEN HARRIS',
 'CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS THAYER)']

In [ ]:
# group by 'Sex' and apply the count function to all columns in each group
df.groupby('Sex').apply(lambda x: x.count())

/tmp/ipython-input-2580884972.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Sex').apply(lambda x: x.count())


PassengerId  Survived  Pclass  Name  Sex  Age  SibSp  Parch  Ticket  \
Sex                                                                           
female          314       314     314   314  314  261    314    314     314   
male            577       577     577   577  577  453    577    577     577   

        Fare  Cabin  Embarked  
Sex                            
female   314     97       312  
male     577    107       577